sudo: false
language: python
python:
  - 3.5

cache: false

env:
  - TOX_ENV=py34
  - TOX_ENV=py35
  - TOX_ENV=py36
#  - TOX_ENV=lint

install:
  - pip install -r requirements-dev.txt

script:
  - tox -e $TOX_ENV

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/a57f158d4365b3598713
    on_success: always
    on_failure: always
    on_start: never
